spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather
    platform: postgres
    username: user1
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none  # 데이터베이스 스키마 자동 변경 방지
    show-sql: false  # SQL 쿼리 로그 활성화
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true  # DDL 생성을 비활성화
